// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de_DE": &dictionary{index: de_DEIndex, data: de_DEData},
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"zh_CN": &dictionary{index: zh_CNIndex, data: zh_CNData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	" (%d selected)":                      37,
	"%d items":                            169,
	"%d of %d":                            33,
	"'%s' into '%s'":                      114,
	"@preview/package:version (optional)": 100,
	"A folder with this name will be created at the location above.": 102,
	"A new version is avaliable: %s":                                 194,
	"AI Assistant":                                                   155,
	"About":                                                          353,
	"Agent":                                                          224,
	"Agent Name":                                                     250,
	"Agent Registry":                                                 226,
	"All":                                                            223,
	"All files":                                                      182,
	"Are you sure you want to delete '%s'?":                          109,
	"Are you sure you want to move":                                  113,
	"Are you sure you want to open file '%s'?": 141,
	"Args":                         6,
	"Assistant":                    190,
	"Author":                       198,
	"Authors:":                     235,
	"Auto Save Interval":           284,
	"Bibliography File Name":       66,
	"Browse Packages/Templates...": 50,
	"Browsing thousands of packages and templates on TPIX server, including public namespaces, and private namespaces of your teams.": 209,
	"Build":            147,
	"Build And Export": 116,
	"Bundle":           145,
	"Bundle the project files to a valid Typst package/template.":                                                                                  146,
	"By default a tagged PDF is generated to provide base accessibility. In some cases this may be not desired. You can check this to disable it.": 131,
	"Cached":                   197,
	"Cancel":                   111,
	"Category":                 201,
	"Change":                   310,
	"Change File Indentation":  133,
	"Change tab display size.": 137,
	"Changelog":                350,
	"Check Update":             281,
	"Check for updates on app startup. Please enable it to keep up to date for new features and bugfixes.": 282,
	"Check new version": 349,
	"Choose Document for notes, articles, books, or slides. Choose Package or Template only when developing reusable Typst packages.": 92,
	"Choose folder": 41,
	"Choose how much editor space the preview uses when it opens. You can still drag the divider while editing.": 287,
	"Choose the default presentation for folders, notebooks, and files.":                                         317,
	"Choose the indentation style for the current file.":                                                         135,
	"Choose your Library folder":                               39,
	"Choose your favorite color theme for the user interface.": 276,
	"Classic":          302,
	"Classic controls": 323,
	"Classic keeps Typstify's existing file workflow. Student adds a Library home and focused project navigation.": 301,
	"Clear":          206,
	"Collection: %s": 81,
	"Collections":    68,
	"Command":        252,
	"Configure agent for AI assitant. You can either manually configure your own agent, or select one from the Agent Registry below.": 225,
	"Confirm":                 108,
	"Convert the indentation": 138,
	"Convert the indentation from spaces to tabs or from tabs to spaces, depending on what you choosed.": 139,
	"Copy":             21,
	"Copy import path": 203,
	"Crafting Typst documents at the speed of thought.": 45,
	"Create":                   83,
	"Create In":                95,
	"Create New Project":       82,
	"Create project error: %s": 90,
	"Created Bundle: %s":       148,
	"Creating managed bibliography error: %s":     64,
	"Creating managed bibliography succeeded: %s": 65,
	"Current project or folder":                   314,
	"Cut":                                         22,
	"Debug Log":                                   263,
	"Delete File/Folder":                          107,
	"Description":                                 3,
	"Disable PDF Tags":                            130,
	"Document":                                    106,
	"Download":                                    196,
	"Download package failed: ":                   218,
	"Download the archive for your platform, extract it, and ensure the binary is on your PATH.": 246,
	"Downloaded package %s and %d transitive dependencies.":                                      220,
	"Downloaded package %s. ":            219,
	"Editor":                             298,
	"Editor files":                       312,
	"Enable Partial Preview":             261,
	"Env":                                7,
	"Environment":                        255,
	"Exit":                               38,
	"Explorer":                           157,
	"Export":                             117,
	"Export Dir":                         331,
	"Exported File Format":               119,
	"Exporting file...":                  118,
	"External LSP Server(Tinymist) Path": 279,
	"External Typst Compiler Path":       277,
	"Extra Font Path":                    329,
	"Extra environment variables, space-separated KEY=value pairs, e.g. FOO=bar BAZ=qux": 256,
	"FOO=bar BAZ=qux":            257,
	"File":                       175,
	"File Explorer":              193,
	"File Interface":             299,
	"File Name":                  122,
	"Files":                      188,
	"Find & Replace":             24,
	"Folder":                     161,
	"Font Family":                274,
	"Font Weight":                291,
	"Forget":                     311,
	"Format:":                    77,
	"Found %d local templates.":  222,
	"Found %d packages.":         221,
	"General":                    283,
	"Generate Dependencies file": 339,
	"Getting Started":            47,
	"Go to download":             352,
	"Grid":                       318,
	"Hide Explorer":              183,
	"ID":                         1,
	"ID:":                        232,
	"If the agent fails to start, try installing manually: npm install -g %s": 239,
	"If the agent fails to start, try installing manually: uv pip install %s": 243,
	"Ignore Compiler Embedded Fonts":                                          337,
	"Ignore System Fonts":                                                     335,
	"Ignore embedded Fonts or not. This only works when exporting files.":     338,
	"Ignore system fonts or not. For code linter, auto-completion and previewing, it needs to restart or reload to take effect.": 336,
	"Images":                     180,
	"Indent with spaces or tabs": 134,
	"Indentation":                295,
	"Installation":               247,
	"Installation (Binary)":      245,
	"Installation (npx)":         240,
	"Installation (uvx)":         244,
	"Interface":                  300,
	"Language":                   268,
	"Language Server":            267,
	"Last Updated":               199,
	"Later":                      195,
	"Learn more":                 51,
	"Library":                    184,
	"Library folder":             307,
	"Library rail":               322,
	"Library view":               316,
	"Library: %s":                80,
	"License":                    200,
	"License:":                   234,
	"Line Height Scale":          293,
	"Link":                       4,
	"List":                       319,
	"Ln %d, Col %d":              36,
	"Load External Inputs":       333,
	"Load external inputs from a file named sys-inputs.json as sys.inputs. If there is no such one, it is created at the root dir. \nA sys-inputs.json file contains user defined key-value pairs which can be accessed via Typst's sys.inputs. The values should always be string encoded data.\nNeed to restart or reload to take effect for code linter, auto-completion, and preview when changed.": 334,
	"Loading collecions...": 70,
	"Loading namespaces...": 151,
	"Loading packages...":   204,
	"Loading...":            342,
	"Local Templates":       192,
	"Lock":                  25,
	"Login TPIX":            346,
	"Login TPIX to access all the features of Typstify, including package management, Zotero sync, MCP tools for AI assistant etc. Some features may need a subscription.": 345,
	"Logout TPIX":                     344,
	"MCP":                             228,
	"Match Case":                      29,
	"More":                            191,
	"Move File/Folder":                112,
	"Name":                            2,
	"Namespace":                       149,
	"Namespace: %s":                   79,
	"Navigation":                      320,
	"New":                             170,
	"New File":                        171,
	"New Folder":                      172,
	"New Project":                     173,
	"New chat":                        60,
	"New project...":                  48,
	"No Library folder selected":      309,
	"No PDF Tags":                     132,
	"No collections found":            71,
	"No items match this filter.":     167,
	"No messages.":                    15,
	"No open project.":                159,
	"No packages/templates found":     205,
	"No previous chats yet.":          61,
	"No project":                      158,
	"No results":                      32,
	"No writable namespaces":          152,
	"Not a package creation request.": 87,
	"Notebook":                        174,
	"Notebooks":                       177,
	"Off":                             11,
	"On":                              12,
	"Open AI Assistant: %s + L":       57,
	"Open File Location":              357,
	"Open File With...":               140,
	"Open Folder":                     185,
	"Open Folder Location":            358,
	"Open existing project...":        49,
	"Open/Hide Console: %s + K":       55,
	"Open/Hide File Explorer: %s + D": 54,
	"Open/Hide Previewer: %s + P":     56,
	"Optionally start from a Typst package such as @preview/aero-check:0.1.1. Leave this empty to create a basic document.": 99,
	"Options":       13,
	"Other files":   181,
	"Outline":       189,
	"PDF Standards": 128,
	"PDF Versions":  126,
	"PDF standards that Typstify will enforce conformance with.": 129,
	"PDF version that Typstify will enforce conformance with.":   127,
	"PDFs":              179,
	"PPI":               124,
	"Package":           104,
	"Package Cache Dir": 327,
	"Package Dir":       325,
	"Package kind":      213,
	"Pages":             120,
	"Paste":             23,
	"Paste asset: %s":   156,
	"Personal @local packages and templates from Typst's local package folder. No account or network connection is required.": 211,
	"Plan": 17,
	"Please choose a method to authenticate the agent:":                 0,
	"Please input a valid full template name.":                          86,
	"Please open a folder in File Explorer to place the project files.": 85,
	"Please select where the project should be created.":                89,
	"Please set a name for your package/template.":                      88,
	"Please set a name for your project.":                               84,
	"Power Saving":                                                      265,
	"Preview":                                                           154,
	"Preview In Browser":                                                259,
	"Preview width":                                                     286,
	"Project":                                                           160,
	"Project Location":                                                  93,
	"Project Name":                                                      101,
	"Project Type":                                                      91,
	"Project name":                                                      103,
	"Publish Package":                                                   142,
	"Query packages failed: ":                                           216,
	"Query packages...":                                                 215,
	"Raw Input":                                                         18,
	"Raw Output":                                                        19,
	"Read the docs":                                                     202,
	"Ready — npx is available on your system.":                          237,
	"Ready — uvx is available on your system.":                          241,
	"Refresh":                                                           231,
	"Release Time":                                                      351,
	"Replace":                                                           34,
	"Replace All":                                                       35,
	"Repository:":                                                       236,
	"Required environment variables:":                                   5,
	"Requires Node.js. Install from https://nodejs.org, then restart Typstify.":                       238,
	"Requires uvx. Install via `pip install uv` or https://docs.astral.sh/uv, then restart Typstify.": 242,
	"Search & Replace":                  153,
	"Search TPIX...":                    210,
	"Search local templates...":         212,
	"Search packages/templates on TPIX": 208,
	"See https://agentclientprotocol.com/get-started/registry": 249,
	"Select a directory": 97,
	"Select an agent below or edit directly, e.g. npx -y @scope/package":                                                                     253,
	"Select an agent below or type a name directly.":                                                                                         251,
	"Select an agent from the registry. Click use to overwrite the above configuration.":                                                     227,
	"Select the collection to sync with. Make sure you or your team have added Zotero API key on TPIX server. ":                              69,
	"Select the folder that contains your courses, notebooks, and documents. Typstify keeps it as a normal folder.":                          40,
	"Select the folder where the project will be created.":                                                                                   94,
	"Select the namespace to publish to. Make sure you have logged in TPIX in the app and have accessible namespaces of your TPIX account. ": 150,
	"Send":     9,
	"Sessions": 59,
	"Set font size for the editor. The unit is in scale-independent pixel (sp).":                                                                                                             290,
	"Set font size for the user interface. The unit is in scale-independent pixel (sp).":                                                                                                     271,
	"Set how many number of spaces the Tab is equal to. Please be noted that this works only for empty file. Indentation for non-empty files are auto detected.":                             297,
	"Set the auto save delay (in seconds), cannot be completely disabled.":                                                                                                                   285,
	"Set the desired fonts for the UI. Use CSS style font family syntax which is a list of comma separated names. You can also leave it empty to let the application choose a fallback.":     273,
	"Set the desired fonts for the editor. Use CSS style font family syntax which is a list of comma separated names. You can also leave it empty to let the application choose a fallback.": 288,
	"Set the displaying language of the user interface.":                                                                                                                                     269,
	"Set the expected characters to use when pressing the Tab key. Please be noted that this works only for empty file. Indentation for non-empty files are auto detected.":                  296,
	"Set the expected weight (or boldness) of the text. This is for variable fonts only.":                                                                                                    292,
	"Set the line height scale of the lines in editor. Line height scale is multiplied by line height to determine the final gap between lines.":                                             294,
	"Settings": 187,
	"Show only the current project or folder, or keep the complete workspace tree.": 313,
	"Sign In": 42,
	"Specifies a path to your own version of Tinymist. Leave it empty to use the built-in one. Please check the compatibility before you switch. It needs to restart to take effect.":       280,
	"Specifies a path to your own version of Typst compiler. Leave it empty to use the built-in one. Please check the compatibility before you switch. It needs to restart to take effect.": 278,
	"Specifies where to store your local Typst packages/templates. Leave it empty to use the default dir.":                                                                                  326,
	"Specifies where to store your the cached Typst packages/templates retrieved from the network. Leave it empty to use the default dir.":                                                  328,
	"Start":                    43,
	"Starting AI Assistant...": 58,
	"Stop":                     10,
	"Student":                  303,
	"Student preferences":      305,
	"Submit":                   63,
	"Sync Bibliographies":      165,
	"Sync Bibliography":        62,
	"Sync Dependencies":        164,
	"TPIX":                     341,
	"Tab Width":                136,
	"Template":                 105,
	"Terminal: %s":             20,
	"Text Size":                289,
	"The PPI (pixels per inch) to use for PNG export.": 125,
	"The built-in MCP server use dynamic network port by default, and it registers itself to agent at runtime. \nSome agents does not support runtime registration, you have to fix the MCP server port and register the server manually. When using static port, the server address is 127.0.0.1:5322, transport: http.": 229,
	"The directory to save exported files to, including the deps.json. If not set, the exported files will be saved to a 'output' folder beside the source file.":                                                                                                                                                         332,
	"The directory where to search for fonts when exporting, previewing and auto-completing. Be aware that the current project root directory is always searched. Need to restart or reload to take effect.":                                                                                                              330,
	"The folder shown when Student mode starts. Forgetting it does not delete any files.": 308,
	"The format of the output file.": 115,
	"The name of the managed bibliography file, such as 'bib-file-name.bib'. You can leave it empty to use a auto generated one.":                                  67,
	"The path of the managed bibliography file. Clicking unlink below will turn it to a regular file, and it will not sync with remote Zotero collection anymore.": 76,
	"The previewer will only render pages inside the viewport if enabled. This improves performance especially for large document.":                                262,
	"The project will be created inside the current Library folder.":                                                                                               96,
	"Theme": 275,
	"These choices apply immediately and do not change the Classic interface.": 306,
	"Thinking": 16,
	"This agent is not directly available for your platform. Visit the ACP registry for more details.":                                                                            248,
	"This folder is empty. Use New to create a file, folder, or project.":                                                                                                         168,
	"This specifies the output file name. If multiple files is generated, the file name will be suffixed with a number. When not specified, the name of the source file is used.": 123,
	"To get a subscription of TPIX, click ":                   348,
	"To learn more about TPIX, click ":                        53,
	"To learn more about TPIX, go to ":                        347,
	"To learn more about Typstify, go to ":                    52,
	"Type @ to include resource, and / to use skills.":        14,
	"Type to start a conversation, press Shift+Enter to send": 8,
	"Typst":                                 324,
	"Typst Package Center":                  186,
	"Typst Packages":                        207,
	"Typst Template":                        98,
	"Typst documents":                       178,
	"Typst packages info loaded.":           217,
	"Typst work":                            176,
	"Typstify":                              44,
	"UI Font Family":                        272,
	"UI Text Size":                          270,
	"Unlink":                                73,
	"Unlink managed bibliography error: %s": 74,
	"Unlink managed bibliography succeeded: %s": 75,
	"Unlock":       26,
	"Unwrap Lines": 27,
	"Use":          230,
	"Use Regex":    31,
	"Use template": 214,
	"Use the Library rail, or keep Typstify's familiar sidebar and bottom controls.": 321,
	"Version":                   258,
	"Version:":                  233,
	"View Bibliography Info":    166,
	"View Managed Bibliography": 72,
	"Welcome, %s!":              46,
	"When checked, LSP server runs in power saving mode, only basic syntax checking and code completion are avaliable, diagnostics and previewing will not work. It needs to restart or reload to take effect.": 266,
	"When checked, document preview will be opening in your default browser. Otherwise the preview will use built-in previewer.":                                                                                260,
	"When checked, logs from the built-in LSP (Language Server Procotol) server is written to the console panel. It needs to restart or reload to take effect.":                                                 264,
	"Which pages to export. Valid value can be comma seperated page numbers and page ranges, for example, 1,3,5,6-9. When unspecified, all document pages are exported.":                                        121,
	"Whole Word":            30,
	"Whole workspace":       315,
	"Width: %d, Height: %d": 355,
	"Wrap Lines":            28,
	"Write dependencies of the file compiled to a file named deps.json in your project directory.": 340,
	"You can restore this file from the Trash.":                                                    110,
	"You have an active TPIX session":                                                              343,
	"Your Student preferences are saved and will return when you choose Student.":                  304,
	"Zotero Collection Info":                                                                       78,
	"git checkout %s failed: %v":                                                                   354,
	"npx -y @scope/package":                                                                        254,
	"popup and display the preview in a dedicated window":                                          356,
	"publish package error: %s":                                                                    143,
	"publish package succeeded: %s":                                                                144,
	"pull dependencies error: %s":                                                                  162,
	"pull dependencies succeeded!":                                                                 163,
}

var de_DEIndex = []uint32{ // 360 elements
	// Entry 0 - 1F
	0x00000000, 0x00000042, 0x00000045, 0x0000004a,
	0x00000057, 0x0000005c, 0x0000007e, 0x00000083,
	0x0000008c, 0x000000cd, 0x000000d4, 0x000000da,
	0x000000de, 0x000000e1, 0x000000ea, 0x00000127,
	0x0000013a, 0x00000145, 0x0000014a, 0x00000155,
	0x00000160, 0x00000170, 0x00000179, 0x00000186,
	0x00000190, 0x000001a2, 0x000001aa, 0x000001b5,
	0x000001cd, 0x000001db, 0x000001f2, 0x000001fe,
	// Entry 20 - 3F
	0x0000020e, 0x0000021f, 0x0000022f, 0x00000238,
	0x00000246, 0x00000258, 0x00000271, 0x00000279,
	0x00000296, 0x0000030f, 0x00000321, 0x0000032a,
	0x00000330, 0x00000339, 0x00000368, 0x0000037b,
	0x0000038a, 0x0000039b, 0x000003ba, 0x000003d9,
	0x000003e7, 0x0000041d, 0x0000044e, 0x0000047b,
	0x000004a1, 0x000004c8, 0x000004e8, 0x00000507,
	0x00000511, 0x0000051c, 0x00000539, 0x00000556,
	// Entry 40 - 5F
	0x0000055f, 0x00000599, 0x000005cd, 0x000005e4,
	0x0000067b, 0x00000686, 0x0000072c, 0x00000749,
	0x00000763, 0x00000784, 0x0000079a, 0x000007d4,
	0x0000080c, 0x000008c4, 0x000008cc, 0x000008e1,
	0x000008f2, 0x00000904, 0x00000914, 0x0000092c,
	0x00000936, 0x00000967, 0x000009ba, 0x000009fc,
	0x00000a26, 0x00000a62, 0x00000a93, 0x00000abd,
	0x00000ac8, 0x00000b65, 0x00000b75, 0x00000bb1,
	// Entry 60 - 7F
	0x00000bbe, 0x00000bf8, 0x00000c0f, 0x00000c1d,
	0x00000caa, 0x00000cce, 0x00000cda, 0x00000d1c,
	0x00000d28, 0x00000d2e, 0x00000d36, 0x00000d3f,
	0x00000d55, 0x00000d61, 0x00000d89, 0x00000dc6,
	0x00000dd0, 0x00000de9, 0x00000dff, 0x00000e21,
	0x00000e3e, 0x00000e58, 0x00000e64, 0x00000e7d,
	0x00000e96, 0x00000e9d, 0x00000f57, 0x00000f61,
	0x00001013, 0x00001017, 0x00001054, 0x00001062,
	// Entry 80 - 9F
	0x00001095, 0x000010a3, 0x000010d8, 0x000010ee,
	0x000011c6, 0x000011d5, 0x000011e9, 0x0000120a,
	0x0000123f, 0x0000124a, 0x00001266, 0x0000127a,
	0x000012d7, 0x000012e6, 0x00001317, 0x0000132e,
	0x0000135d, 0x00001386, 0x0000138f, 0x000013d9,
	0x000013e3, 0x000013fb, 0x00001405, 0x000014b6,
	0x000014d3, 0x000014f3, 0x00001507, 0x00001510,
	0x0000151d, 0x00001534, 0x0000153d, 0x0000154a,
	// Entry A0 - BF
	0x00001562, 0x0000156a, 0x00001571, 0x000015a0,
	0x000015c7, 0x000015e7, 0x00001605, 0x00001620,
	0x0000164a, 0x000016b1, 0x000016c0, 0x000016c4,
	0x000016cf, 0x000016dc, 0x000016ea, 0x000016f4,
	0x000016fa, 0x00001709, 0x00001716, 0x00001726,
	0x0000172b, 0x00001732, 0x00001741, 0x0000174e,
	0x00001762, 0x0000176d, 0x0000177c, 0x0000178f,
	0x0000179d, 0x000017a5, 0x000017b0, 0x000017ba,
	// Entry C0 - DF
	0x000017bf, 0x000017cf, 0x000017de, 0x00001806,
	0x0000180e, 0x0000181c, 0x00001830, 0x00001836,
	0x0000184b, 0x00001852, 0x0000185c, 0x00001870,
	0x00001884, 0x0000189d, 0x000018bc, 0x000018c5,
	0x000018d2, 0x000018f2, 0x00001987, 0x0000199b,
	0x00001a26, 0x00001a46, 0x00001a4f, 0x00001a61,
	0x00001a74, 0x00001a96, 0x00001ab8, 0x00001adc,
	0x00001afe, 0x00001b40, 0x00001b57, 0x00001b77,
	// Entry E0 - FF
	0x00001b7c, 0x00001b82, 0x00001c39, 0x00001c4a,
	0x00001cbf, 0x00001cc3, 0x00001e30, 0x00001e3a,
	0x00001e48, 0x00001e4c, 0x00001e55, 0x00001e5d,
	0x00001e66, 0x00001e72, 0x00001ea2, 0x00001f03,
	0x00001f5f, 0x00001f72, 0x00001fa2, 0x0000201e,
	0x0000207a, 0x0000208d, 0x000020a3, 0x00002127,
	0x00002134, 0x000021a6, 0x000021e1, 0x000021ed,
	0x00002238, 0x0000223f, 0x0000229b, 0x000022b1,
	// Entry 100 - 11F
	0x000022ba, 0x00002324, 0x00002334, 0x0000233c,
	0x00002350, 0x000023d3, 0x000023eb, 0x00002471,
	0x00002481, 0x00002527, 0x00002538, 0x00002617,
	0x00002624, 0x0000262c, 0x00002667, 0x00002679,
	0x000026ed, 0x000026ff, 0x000027dc, 0x000027eb,
	0x000027f2, 0x00002837, 0x00002854, 0x00002933,
	0x00002957, 0x00002a2f, 0x00002a3e, 0x00002ac9,
	0x00002ad3, 0x00002af3, 0x00002b6e, 0x00002b7d,
	// Entry 120 - 13F
	0x00002bfb, 0x00002cdc, 0x00002ceb, 0x00002d52,
	0x00002d61, 0x00002dcb, 0x00002dde, 0x00002e92,
	0x00002e99, 0x00002f6a, 0x00003018, 0x0000301f,
	0x00003030, 0x0000303c, 0x000030c4, 0x000030ce,
	0x000030d6, 0x00003140, 0x00003156, 0x000031a6,
	0x000031b8, 0x00003223, 0x00003246, 0x0000324e,
	0x00003258, 0x00003267, 0x000032d5, 0x000032fd,
	0x00003315, 0x00003328, 0x0000336e, 0x00003375,
	// Entry 140 - 15F
	0x0000337b, 0x00003386, 0x000033f3, 0x00003405,
	0x0000341f, 0x00003425, 0x00003436, 0x000034bc,
	0x000034d4, 0x00003584, 0x000035a4, 0x00003699,
	0x000036ab, 0x0000376c, 0x00003783, 0x0000395e,
	0x0000397c, 0x00003a0b, 0x00003a39, 0x00003a9e,
	0x00003abd, 0x00003b2d, 0x00003b32, 0x00003b42,
	0x00003b65, 0x00003b73, 0x00003c5e, 0x00003c6c,
	0x00003c9e, 0x00003cd3, 0x00003ce8, 0x00003cfc,
	// Entry 160 - 17F
	0x00003d13, 0x00003d20, 0x00003d26, 0x00003d4f,
	0x00003d6b, 0x00003d98, 0x00003db1, 0x00003dcb,
} // Size: 1464 bytes

const de_DEData string = "" + // Size: 15819 bytes
	"\x02Bitte wählen Sie eine Methode zur Authentifizierung des Agenten:\x02" +
	"ID\x02Name\x02Beschreibung\x02Link\x02Erforderliche Umgebungsvariablen:" +
	"\x02Args\x02Umgebung\x02Tippen Sie, um ein Gespräch zu beginnen. Mit Shi" +
	"ft+Enter senden\x02Senden\x02Stopp\x02Aus\x02An\x02Optionen\x02@ eingebe" +
	"n, um Ressourcen einzubinden, / um Skills zu nutzen\x02Keine Nachrichten" +
	".\x02Denkt nach\x02Plan\x02Roheingabe\x02Rohausgabe\x02Terminal: %[1]s" +
	"\x02Kopieren\x02Ausschneiden\x02Einfügen\x02Suchen & Ersetzen\x02Sperren" +
	"\x02Entsperren\x02Zeilenumbruch entfernen\x02Zeilenumbruch\x02Groß-/Klei" +
	"nschreibung\x02Ganzes Wort\x02Regex verwenden\x02Keine Ergebnisse\x02%[1" +
	"]d von %[2]d\x02Ersetzen\x02Alle ersetzen\x02Z %[1]d, Sp %[2]d\x04\x01 " +
	"\x00\x14\x02(%[1]d ausgewählt)\x02Beenden\x02Bibliotheksordner auswählen" +
	"\x02Wähle den Ordner mit deinen Kursen, Notizbüchern und Dokumenten. Typ" +
	"stify behandelt ihn weiterhin als normalen Ordner.\x02Ordner auswählen" +
	"\x02Anmelden\x02Start\x02Typstify\x02Typst-Dokumente in Gedankenschnelle" +
	" erstellen.\x02Willkommen, %[1]s!\x02Erste Schritte\x02Neues Projekt..." +
	"\x02Bestehendes Projekt öffnen...\x02Pakete/Vorlagen durchsuchen...\x02M" +
	"ehr erfahren\x04\x00\x01 1\x02Um mehr über Typstify zu erfahren, besuche" +
	"n Sie\x04\x00\x01 ,\x02Um mehr über TPIX zu erfahren, klicken Sie\x02Dat" +
	"ei-Explorer öffnen/ausblenden: %[1]s + D\x02Konsole öffnen/ausblenden: %" +
	"[1]s + K\x02Vorschau öffnen/ausblenden: %[1]s + P\x02KI-Assistent öffnen" +
	": %[1]s + L\x02KI-Assistent wird gestartet...\x02Sitzungen\x02Neuer Chat" +
	"\x02Noch keine vorherigen Chats.\x02Bibliografie synchronisieren\x02Abse" +
	"nden\x02Fehler beim Erstellen der verwalteten Bibliografie: %[1]s\x02Ver" +
	"waltete Bibliografie erfolgreich erstellt: %[1]s\x02Bibliografie-Dateina" +
	"me\x02Der Name der verwalteten Bibliografie-Datei, z. B. 'bib-file-name." +
	"bib'. Lassen Sie das Feld leer, um einen automatisch generierten Namen z" +
	"u verwenden.\x02Sammlungen\x04\x00\x01 \xa0\x01\x02Wählen Sie die zu syn" +
	"chronisierende Sammlung aus. Stellen Sie sicher, dass Sie oder Ihr Team " +
	"den Zotero-API-Schlüssel auf dem TPIX-Server hinzugefügt haben.\x02Samml" +
	"ungen werden geladen...\x02Keine Sammlungen gefunden\x02Verwaltete Bibli" +
	"ografie anzeigen\x02Verknüpfung aufheben\x02Fehler beim Aufheben der Bib" +
	"liografie-Verknüpfung: %[1]s\x02Bibliografie-Verknüpfung erfolgreich auf" +
	"gehoben: %[1]s\x02Der Pfad der verwalteten Bibliografie-Datei. Durch Kli" +
	"cken auf Verknüpfung aufheben wird sie zu einer normalen Datei und nicht" +
	" mehr mit der entfernten Zotero-Sammlung synchronisiert.\x02Format:\x02Z" +
	"otero-Sammlungsinfo\x02Namespace: %[1]s\x02Bibliothek: %[1]s\x02Sammlung" +
	": %[1]s\x02Neues Projekt erstellen\x02Erstellen\x02Bitte geben Sie einen" +
	" Namen für Ihr Projekt an.\x02Bitte öffnen Sie einen Ordner im Datei-Exp" +
	"lorer, um die Projektdateien abzulegen.\x02Bitte geben Sie einen gültige" +
	"n vollständigen Vorlagennamen ein.\x02Keine Anfrage zum Erstellen eines " +
	"Pakets.\x02Bitte geben Sie einen Namen für Ihr Paket/Ihre Vorlage an." +
	"\x02Wähle aus, wo das Projekt erstellt werden soll.\x02Fehler beim Erste" +
	"llen des Projekts: %[1]s\x02Projekttyp\x02Wähle „Dokument“ für Notizen, " +
	"Artikel, Bücher oder Folien. Wähle „Paket“ oder „Vorlage“ nur zur Entwic" +
	"klung wiederverwendbarer Typst-Pakete.\x02Projektstandort\x02Wähle den O" +
	"rdner, in dem das Projekt erstellt werden soll.\x02Erstellen in\x02Das P" +
	"rojekt wird im aktuellen Bibliotheksordner erstellt.\x02Verzeichnis ausw" +
	"ählen\x02Typst-Vorlage\x02Optional kannst du mit einem Typst-Paket wie " +
	"@preview/aero-check:0.1.1 beginnen. Lass das Feld leer, um ein einfaches" +
	" Dokument zu erstellen.\x02@preview/package:version (optional)\x02Projek" +
	"tname\x02Ein Ordner mit diesem Namen wird am oben gewählten Ort erstellt" +
	".\x02Projektname\x02Paket\x02Vorlage\x02Dokument\x02Datei/Ordner löschen" +
	"\x02Bestätigen\x02Möchten Sie '%[1]s' wirklich löschen?\x02Sie können di" +
	"ese Datei aus dem Papierkorb wiederherstellen.\x02Abbrechen\x02Datei/Ord" +
	"ner verschieben\x02Möchten Sie wirklich\x02'%[1]s' nach '%[2]s' verschie" +
	"ben?\x02Das Format der Ausgabedatei.\x02Erstellen und Exportieren\x02Exp" +
	"ortieren\x02Datei wird exportiert...\x02Exportiertes Dateiformat\x02Seit" +
	"en\x02Welche Seiten exportiert werden sollen. Gültige Werte sind durch K" +
	"ommas getrennte Seitenzahlen und Seitenbereiche, z. B. 1,3,5,6-9. Wenn n" +
	"icht angegeben, werden alle Seiten exportiert.\x02Dateiname\x02Gibt den " +
	"Ausgabedateinamen an. Wenn mehrere Dateien generiert werden, wird der Da" +
	"teiname mit einer Nummer versehen. Wenn nicht angegeben, wird der Name d" +
	"er Quelldatei verwendet.\x02PPI\x02Die für den PNG-Export zu verwendende" +
	" PPI (Pixel pro Zoll).\x02PDF-Versionen\x02PDF-Version, deren Konformitä" +
	"t Typstify erzwingt.\x02PDF-Standards\x02PDF-Standards, deren Konformitä" +
	"t Typstify erzwingt.\x02PDF-Tags deaktivieren\x02Standardmäßig wird ein " +
	"getaggtes PDF generiert, um grundlegende Barrierefreiheit zu gewährleist" +
	"en. In einigen Fällen ist dies möglicherweise nicht erwünscht. Aktiviere" +
	"n Sie diese Option, um es zu deaktivieren.\x02Keine PDF-Tags\x02Dateiein" +
	"zug ändern\x02Einzug mit Leerzeichen oder Tabs\x02Wählen Sie den Einzugs" +
	"stil für die aktuelle Datei.\x02Tab-Breite\x02Tab-Anzeigegröße ändern." +
	"\x02Einzug konvertieren\x02Konvertiert den Einzug je nach Auswahl von Le" +
	"erzeichen zu Tabs oder von Tabs zu Leerzeichen.\x02Öffnen mit...\x02Möch" +
	"ten Sie die Datei '%[1]s' wirklich öffnen?\x02Paket veröffentlichen\x02F" +
	"ehler beim Veröffentlichen des Pakets: %[1]s\x02Paket erfolgreich veröff" +
	"entlicht: %[1]s\x02Bündeln\x02Die Projektdateien zu einem gültigen Typst" +
	"-Paket/einer Vorlage bündeln.\x02Erstellen\x02Bündel erstellt: %[1]s\x02" +
	"Namespace\x04\x00\x01 \xab\x01\x02Wählen Sie den Namespace für die Veröf" +
	"fentlichung. Stellen Sie sicher, dass Sie in der App bei TPIX angemeldet" +
	" sind und Zugriff auf Namespaces Ihres TPIX-Kontos haben.\x02Namespaces " +
	"werden geladen...\x02Keine beschreibbaren Namespaces\x02Suchen und Erset" +
	"zen\x02Vorschau\x02KI-Assistent\x02Asset einfügen: %[1]s\x02Explorer\x02" +
	"Kein Projekt\x02Kein Projekt geöffnet.\x02Projekt\x02Ordner\x02Fehler be" +
	"im Abrufen der Abhängigkeiten: %[1]s\x02Abhängigkeiten erfolgreich abger" +
	"ufen!\x02Abhängigkeiten synchronisieren\x02Bibliografien synchronisieren" +
	"\x02Bibliografie-Info anzeigen\x02Keine Elemente entsprechen diesem Filt" +
	"er.\x02Dieser Ordner ist leer. Verwende „Neu“, um eine Datei, einen Ordn" +
	"er oder ein Projekt zu erstellen.\x02%[1]d Elemente\x02Neu\x02Neue Datei" +
	"\x02Neuer Ordner\x02Neues Projekt\x02Notizbuch\x02Datei\x02Typst-Arbeite" +
	"n\x02Notizbücher\x02Typst-Dokumente\x02PDFs\x02Bilder\x02Andere Dateien" +
	"\x02Alle Dateien\x02Explorer ausblenden\x02Bibliothek\x02Ordner öffnen" +
	"\x02Typst-Paketzentrum\x02Einstellungen\x02Dateien\x02Gliederung\x02Assi" +
	"stent\x02Mehr\x02Lokale Vorlagen\x02Datei-Explorer\x02Eine neue Version " +
	"ist verfügbar: %[1]s\x02Später\x02Herunterladen\x02Zwischengespeichert" +
	"\x02Autor\x02Zuletzt aktualisiert\x02Lizenz\x02Kategorie\x02Dokumentatio" +
	"n lesen\x02Importpfad kopieren\x02Pakete werden geladen...\x02Keine Pake" +
	"te/Vorlagen gefunden\x02Löschen\x02Typst-Pakete\x02Pakete/Vorlagen auf T" +
	"PIX suchen\x02Durchsuchen Sie Tausende von Paketen und Vorlagen auf dem " +
	"TPIX-Server, einschließlich öffentlicher Namespaces und privater Namespa" +
	"ces Ihrer Teams.\x02TPIX durchsuchen...\x02Persönliche @local-Pakete und" +
	" -Vorlagen aus Typsts lokalem Paketordner. Es ist weder ein Konto noch e" +
	"ine Netzwerkverbindung erforderlich.\x02Lokale Vorlagen durchsuchen …" +
	"\x02Paketart\x02Vorlage verwenden\x02Pakete abfragen...\x04\x00\x01 \x1d" +
	"\x02Paketabfrage fehlgeschlagen:\x02Typst-Paketinformationen geladen." +
	"\x04\x00\x01 \x1f\x02Paket-Download fehlgeschlagen:\x04\x00\x01 \x1d\x02" +
	"Paket %[1]s heruntergeladen.\x02Paket %[1]s und %[2]d transitive Abhängi" +
	"gkeiten heruntergeladen.\x02%[1]d Pakete gefunden.\x02%[1]d lokale Vorla" +
	"gen gefunden.\x02Alle\x02Agent\x02Konfigurieren Sie den Agenten für den " +
	"KI-Assistenten. Sie können entweder Ihren eigenen Agenten manuell konfig" +
	"urieren oder einen aus der untenstehenden Agenten-Registry auswählen." +
	"\x02Agenten-Registry\x02Wählen Sie einen Agenten aus der Registry. Klick" +
	"en Sie auf Verwenden, um die obige Konfiguration zu überschreiben.\x02MC" +
	"P\x02Der integrierte MCP-Server verwendet standardmäßig einen dynamische" +
	"n Netzwerkport und registriert sich zur Laufzeit beim Agenten.\x0aEinige" +
	" Agenten unterstützen keine Laufzeitregistrierung. Sie müssen den MCP-Se" +
	"rver-Port festlegen und den Server manuell registrieren. Bei Verwendung " +
	"eines statischen Ports lautet die Serveradresse 127.0.0.1:5322, Transpor" +
	"t: http.\x02Verwenden\x02Aktualisieren\x02ID:\x02Version:\x02Lizenz:\x02" +
	"Autoren:\x02Repository:\x02Bereit — npx ist auf Ihrem System verfügbar." +
	"\x02Erfordert Node.js. Installieren Sie es von https://nodejs.org und st" +
	"arten Sie dann Typstify neu.\x02Wenn der Agent nicht startet, versuchen " +
	"Sie die manuelle Installation: npm install -g %[1]s\x02Installation (npx" +
	")\x02Bereit — uvx ist auf Ihrem System verfügbar.\x02Erfordert uvx. Inst" +
	"allieren Sie es über `pip install uv` oder https://docs.astral.sh/uv und" +
	" starten Sie dann Typstify neu.\x02Wenn der Agent nicht startet, versuch" +
	"en Sie die manuelle Installation: uv pip install %[1]s\x02Installation (" +
	"uvx)\x02Installation (Binär)\x02Laden Sie das Archiv für Ihre Plattform " +
	"herunter, entpacken Sie es und stellen Sie sicher, dass die Binärdatei i" +
	"n Ihrem PATH ist.\x02Installation\x02Dieser Agent ist für Ihre Plattform" +
	" nicht direkt verfügbar. Besuchen Sie die ACP-Registry für weitere Detai" +
	"ls.\x02Siehe https://agentclientprotocol.com/get-started/registry\x02Age" +
	"ntenname\x02Wählen Sie unten einen Agenten aus oder geben Sie direkt ein" +
	"en Namen ein.\x02Befehl\x02Wählen Sie unten einen Agenten aus oder bearb" +
	"eiten Sie direkt, z. B. npx -y @scope/package\x02npx -y @scope/package" +
	"\x02Umgebung\x02Zusätzliche Umgebungsvariablen, durch Leerzeichen getren" +
	"nte SCHLÜSSEL=Wert-Paare, z. B. FOO=bar BAZ=qux\x02FOO=bar BAZ=qux\x02Ve" +
	"rsion\x02Vorschau im Browser\x02Wenn aktiviert, wird die Dokumentvorscha" +
	"u in Ihrem Standardbrowser geöffnet. Andernfalls wird die integrierte Vo" +
	"rschau verwendet.\x02Teilvorschau aktivieren\x02Wenn aktiviert, rendert " +
	"die Vorschau nur Seiten im sichtbaren Bereich. Dies verbessert besonders" +
	" bei großen Dokumenten die Leistung.\x02Debug-Protokoll\x02Wenn aktivier" +
	"t, werden Protokolle des integrierten LSP-Servers (Language Server Proto" +
	"col) im Konsolenbereich ausgegeben. Ein Neustart oder Neuladen ist erfor" +
	"derlich.\x02Energiesparmodus\x02Wenn aktiviert, läuft der LSP-Server im " +
	"Energiesparmodus. Nur grundlegende Syntaxprüfung und Codevervollständigu" +
	"ng sind verfügbar, Diagnose und Vorschau funktionieren nicht. Ein Neusta" +
	"rt oder Neuladen ist erforderlich.\x02Sprachserver\x02Sprache\x02Legen S" +
	"ie die Anzeigesprache der Benutzeroberfläche fest.\x02UI-Schriftgröße" +
	"\x02Legen Sie die Schriftgröße für die Benutzeroberfläche fest. Die Einh" +
	"eit ist skalierungsunabhängige Pixel (sp).\x02UI-Schriftfamilie\x02Legen" +
	" Sie die gewünschten Schriftarten für die UI fest. Verwenden Sie die CSS" +
	"-Schriftfamilien-Syntax als kommagetrennte Liste. Sie können das Feld au" +
	"ch leer lassen, damit die Anwendung eine Fallback-Schriftart wählt.\x02S" +
	"chriftfamilie\x02Design\x02Wählen Sie Ihr bevorzugtes Farbdesign für die" +
	" Benutzeroberfläche.\x02Externer Typst-Compiler-Pfad\x02Gibt einen Pfad " +
	"zu Ihrer eigenen Version des Typst-Compilers an. Lassen Sie das Feld lee" +
	"r, um die integrierte Version zu verwenden. Bitte überprüfen Sie die Kom" +
	"patibilität vor dem Wechsel. Ein Neustart ist erforderlich.\x02Externer " +
	"LSP-Server-Pfad (Tinymist)\x02Gibt einen Pfad zu Ihrer eigenen Version v" +
	"on Tinymist an. Lassen Sie das Feld leer, um die integrierte Version zu " +
	"verwenden. Bitte überprüfen Sie die Kompatibilität vor dem Wechsel. Ein " +
	"Neustart ist erforderlich.\x02Update prüfen\x02Beim App-Start nach Updat" +
	"es suchen. Bitte aktivieren Sie dies, um über neue Funktionen und Fehler" +
	"behebungen auf dem Laufenden zu bleiben.\x02Allgemein\x02Automatisches S" +
	"peicherintervall\x02Legen Sie die Verzögerung für das automatische Speic" +
	"hern fest (in Sekunden). Kann nicht vollständig deaktiviert werden.\x02V" +
	"orschaubreite\x02Wähle, wie viel Platz die Vorschau beim Öffnen im Edito" +
	"r verwendet. Du kannst den Trenner beim Bearbeiten weiterhin ziehen.\x02" +
	"Legen Sie die gewünschten Schriftarten für den Editor fest. Verwenden Si" +
	"e die CSS-Schriftfamilien-Syntax als kommagetrennte Liste. Sie können da" +
	"s Feld auch leer lassen, damit die Anwendung eine Fallback-Schriftart wä" +
	"hlt.\x02Schriftgröße\x02Legen Sie die Schriftgröße für den Editor fest. " +
	"Die Einheit ist skalierungsunabhängige Pixel (sp).\x02Schriftstärke\x02L" +
	"egen Sie die erwartete Stärke (oder Fettung) des Textes fest. Dies gilt " +
	"nur für variable Schriftarten.\x02Zeilenhöhenfaktor\x02Legen Sie den Zei" +
	"lenhöhenfaktor für den Editor fest. Der Zeilenhöhenfaktor wird mit der Z" +
	"eilenhöhe multipliziert, um den endgültigen Abstand zwischen den Zeilen " +
	"zu bestimmen.\x02Einzug\x02Legen Sie die erwarteten Zeichen fest, die be" +
	"im Drücken der Tabulatortaste verwendet werden. Beachten Sie, dass dies " +
	"nur für leere Dateien gilt. Der Einzug für nicht-leere Dateien wird auto" +
	"matisch erkannt.\x02Legen Sie fest, wie vielen Leerzeichen ein Tab entsp" +
	"richt. Beachten Sie, dass dies nur für leere Dateien gilt. Der Einzug fü" +
	"r nicht-leere Dateien wird automatisch erkannt.\x02Editor\x02Dateioberfl" +
	"äche\x02Oberfläche\x02„Klassisch“ behält Typstifys bisherigen Dateiabla" +
	"uf bei. „Student“ ergänzt eine Bibliothek und fokussierte Projektnavigat" +
	"ion.\x02Klassisch\x02Student\x02Deine Student-Einstellungen werden gespe" +
	"ichert und wiederhergestellt, sobald du „Student“ auswählst.\x02Student-" +
	"Einstellungen\x02Diese Einstellungen gelten sofort und ändern die klassi" +
	"sche Oberfläche nicht.\x02Bibliotheksordner\x02Dieser Ordner wird beim S" +
	"tart des Studentenmodus angezeigt. Beim Vergessen werden keine Dateien g" +
	"elöscht.\x02Kein Bibliotheksordner ausgewählt\x02Ändern\x02Vergessen\x02" +
	"Editor-Dateien\x02Zeige nur das aktuelle Projekt bzw. den aktuellen Ordn" +
	"er oder behalte den vollständigen Arbeitsbereichsbaum.\x02Aktuelles Proj" +
	"ekt oder aktueller Ordner\x02Gesamter Arbeitsbereich\x02Bibliotheksansic" +
	"ht\x02Wähle die Standarddarstellung für Ordner, Notizbücher und Dateien." +
	"\x02Raster\x02Liste\x02Navigation\x02Verwende die Bibliotheksleiste oder" +
	" behalte Typstifys vertraute Seitenleiste und die unteren Bedienelemente" +
	".\x02Bibliotheksleiste\x02Klassische Bedienelemente\x02Typst\x02Paketver" +
	"zeichnis\x02Gibt an, wo Ihre lokalen Typst-Pakete/Vorlagen gespeichert w" +
	"erden. Lassen Sie das Feld leer, um das Standardverzeichnis zu verwenden" +
	".\x02Paket-Cache-Verzeichnis\x02Gibt an, wo die aus dem Netzwerk abgeruf" +
	"enen zwischengespeicherten Typst-Pakete/Vorlagen gespeichert werden. Las" +
	"sen Sie das Feld leer, um das Standardverzeichnis zu verwenden.\x02Zusät" +
	"zlicher Schriftarten-Pfad\x02Das Verzeichnis, in dem beim Exportieren, V" +
	"orschauen und automatischen Vervollständigen nach Schriftarten gesucht w" +
	"ird. Beachten Sie, dass das aktuelle Projektstammverzeichnis immer durch" +
	"sucht wird. Ein Neustart oder Neuladen ist erforderlich.\x02Exportverzei" +
	"chnis\x02Das Verzeichnis zum Speichern exportierter Dateien, einschließl" +
	"ich deps.json. Wenn nicht festgelegt, werden die exportierten Dateien in" +
	" einem 'output'-Ordner neben der Quelldatei gespeichert.\x02Externe Eing" +
	"aben laden\x02Lädt externe Eingaben aus einer Datei namens sys-inputs.js" +
	"on als sys.inputs. Wenn keine vorhanden ist, wird sie im Stammverzeichni" +
	"s erstellt.\x0aEine sys-inputs.json-Datei enthält benutzerdefinierte Sch" +
	"lüssel-Wert-Paare, auf die über Typsts sys.inputs zugegriffen werden kan" +
	"n. Die Werte sollten immer als Zeichenkette codierte Daten sein.\x0aEin " +
	"Neustart oder Neuladen ist erforderlich, damit Änderungen für Code-Prüfu" +
	"ng, Autovervollständigung und Vorschau wirksam werden.\x02Systemschrifta" +
	"rten ignorieren\x02Systemschriftarten ignorieren oder nicht. Für Code-Pr" +
	"üfung, Autovervollständigung und Vorschau ist ein Neustart oder Neulade" +
	"n erforderlich.\x02Eingebettete Compiler-Schriftarten ignorieren\x02Eing" +
	"ebettete Schriftarten ignorieren oder nicht. Dies funktioniert nur beim " +
	"Exportieren von Dateien.\x02Abhängigkeitsdatei generieren\x02Schreibt di" +
	"e Abhängigkeiten der kompilierten Datei in eine Datei namens deps.json i" +
	"n Ihrem Projektverzeichnis.\x02TPIX\x02Wird geladen...\x02Sie haben eine" +
	" aktive TPIX-Sitzung\x02TPIX abmelden\x02Melden Sie sich bei TPIX an, um" +
	" auf alle Funktionen von Typstify zuzugreifen, einschließlich Paketverwa" +
	"ltung, Zotero-Synchronisierung, MCP-Tools für den KI-Assistenten usw. Ei" +
	"nige Funktionen erfordern möglicherweise ein Abonnement.\x02TPIX anmelde" +
	"n\x04\x00\x01 -\x02Um mehr über TPIX zu erfahren, besuchen Sie\x04\x00" +
	"\x01 0\x02Um ein TPIX-Abonnement zu erhalten, klicken Sie\x02Neue Versio" +
	"n prüfen\x02Änderungsprotokoll\x02Veröffentlichungszeit\x02Zum Download" +
	"\x02Über\x02git checkout %[1]s fehlgeschlagen: %[2]v\x02Breite: %[1]d, H" +
	"öhe: %[2]d\x02Vorschau in einem separaten Fenster anzeigen\x02Dateispei" +
	"cherort öffnen\x02Ordnerspeicherort öffnen"

var en_USIndex = []uint32{ // 360 elements
	// Entry 0 - 1F
	0x00000000, 0x00000032, 0x00000035, 0x0000003a,
	0x00000046, 0x0000004b, 0x0000006b, 0x00000070,
	0x00000074, 0x000000ac, 0x000000b1, 0x000000b6,
	0x000000ba, 0x000000bd, 0x000000c5, 0x000000f6,
	0x00000103, 0x0000010c, 0x00000111, 0x0000011b,
	0x00000126, 0x00000136, 0x0000013b, 0x0000013f,
	0x00000145, 0x00000154, 0x00000159, 0x00000160,
	0x0000016d, 0x00000178, 0x00000183, 0x0000018e,
	// Entry 20 - 3F
	0x00000198, 0x000001a3, 0x000001b2, 0x000001ba,
	0x000001c6, 0x000001da, 0x000001f0, 0x000001f5,
	0x00000210, 0x0000027e, 0x0000028c, 0x00000294,
	0x0000029a, 0x000002a3, 0x000002d5, 0x000002e5,
	0x000002f5, 0x00000304, 0x0000031d, 0x0000033a,
	0x00000345, 0x0000036e, 0x00000393, 0x000003b6,
	0x000003d3, 0x000003f2, 0x0000040f, 0x00000428,
	0x00000431, 0x0000043a, 0x00000451, 0x00000463,
	// Entry 40 - 5F
	0x0000046a, 0x00000495, 0x000004c4, 0x000004db,
	0x00000557, 0x00000563, 0x000005d1, 0x000005e7,
	0x000005fc, 0x00000616, 0x0000061d, 0x00000646,
	0x00000673, 0x00000710, 0x00000718, 0x0000072f,
	0x00000740, 0x0000074f, 0x00000761, 0x00000774,
	0x0000077b, 0x0000079f, 0x000007e1, 0x0000080a,
	0x0000082a, 0x00000857, 0x0000088a, 0x000008a6,
	0x000008b3, 0x00000933, 0x00000944, 0x00000979,
	// Entry 60 - 7F
	0x00000983, 0x000009c2, 0x000009d5, 0x000009e4,
	0x00000a5a, 0x00000a7e, 0x00000a8b, 0x00000aca,
	0x00000ad7, 0x00000adf, 0x00000ae8, 0x00000af1,
	0x00000b04, 0x00000b0c, 0x00000b35, 0x00000b5f,
	0x00000b66, 0x00000b77, 0x00000b95, 0x00000baa,
	0x00000bc9, 0x00000bda, 0x00000be1, 0x00000bf3,
	0x00000c08, 0x00000c0e, 0x00000cb1, 0x00000cbb,
	0x00000d67, 0x00000d6b, 0x00000d9c, 0x00000da9,
	// Entry 80 - 9F
	0x00000de2, 0x00000df0, 0x00000e2b, 0x00000e3c,
	0x00000ec9, 0x00000ed5, 0x00000eed, 0x00000f08,
	0x00000f3b, 0x00000f45, 0x00000f5e, 0x00000f76,
	0x00000fd9, 0x00000feb, 0x00001017, 0x00001027,
	0x00001044, 0x00001065, 0x0000106c, 0x000010a8,
	0x000010ae, 0x000010c4, 0x000010ce, 0x0000115a,
	0x00001170, 0x00001187, 0x00001198, 0x000011a0,
	0x000011ad, 0x000011c0, 0x000011c9, 0x000011d4,
	// Entry A0 - BF
	0x000011e5, 0x000011ed, 0x000011f4, 0x00001213,
	0x00001230, 0x00001242, 0x00001256, 0x0000126d,
	0x00001289, 0x000012cd, 0x000012d9, 0x000012dd,
	0x000012e6, 0x000012f1, 0x000012fd, 0x00001306,
	0x0000130b, 0x00001316, 0x00001320, 0x00001330,
	0x00001335, 0x0000133c, 0x00001348, 0x00001352,
	0x00001360, 0x00001368, 0x00001374, 0x00001389,
	0x00001392, 0x00001398, 0x000013a0, 0x000013aa,
	// Entry C0 - DF
	0x000013af, 0x000013bf, 0x000013cd, 0x000013ef,
	0x000013f5, 0x000013fe, 0x00001405, 0x0000140c,
	0x00001419, 0x00001421, 0x0000142a, 0x00001438,
	0x00001449, 0x0000145d, 0x00001479, 0x0000147f,
	0x0000148e, 0x000014b0, 0x00001530, 0x0000153f,
	0x000015b7, 0x000015d1, 0x000015de, 0x000015eb,
	0x000015fd, 0x00001619, 0x00001635, 0x00001653,
	0x00001672, 0x000016ae, 0x000016c4, 0x000016e1,
	// Entry E0 - FF
	0x000016e5, 0x000016eb, 0x0000176b, 0x0000177a,
	0x000017cd, 0x000017d1, 0x00001904, 0x00001908,
	0x00001910, 0x00001914, 0x0000191d, 0x00001926,
	0x0000192f, 0x0000193b, 0x00001966, 0x000019b0,
	0x000019fb, 0x00001a0e, 0x00001a39, 0x00001a99,
	0x00001ae4, 0x00001af7, 0x00001b0d, 0x00001b68,
	0x00001b75, 0x00001bd6, 0x00001c0f, 0x00001c1a,
	0x00001c49, 0x00001c51, 0x00001c94, 0x00001caa,
	// Entry 100 - 11F
	0x00001cb6, 0x00001d09, 0x00001d19, 0x00001d21,
	0x00001d34, 0x00001daf, 0x00001dc6, 0x00001e44,
	0x00001e4e, 0x00001ee8, 0x00001ef5, 0x00001fbf,
	0x00001fcf, 0x00001fd8, 0x0000200b, 0x00002018,
	0x0000206b, 0x0000207a, 0x0000212d, 0x00002139,
	0x0000213f, 0x00002178, 0x00002195, 0x0000224b,
	0x0000226e, 0x0000231e, 0x0000232b, 0x00002390,
	0x00002398, 0x000023ab, 0x000023f0, 0x000023fe,
	// Entry 120 - 13F
	0x00002469, 0x00002520, 0x0000252a, 0x00002575,
	0x00002581, 0x000025d5, 0x000025e7, 0x00002672,
	0x0000267e, 0x00002724, 0x000027bf, 0x000027c6,
	0x000027d5, 0x000027df, 0x0000284c, 0x00002854,
	0x0000285c, 0x000028a8, 0x000028bc, 0x00002905,
	0x00002914, 0x00002968, 0x00002983, 0x0000298a,
	0x00002991, 0x0000299e, 0x000029ec, 0x00002a06,
	0x00002a16, 0x00002a23, 0x00002a66, 0x00002a6b,
	// Entry 140 - 15F
	0x00002a70, 0x00002a7b, 0x00002aca, 0x00002ad7,
	0x00002ae8, 0x00002aee, 0x00002afa, 0x00002b5f,
	0x00002b71, 0x00002bf6, 0x00002c06, 0x00002ccd,
	0x00002cd8, 0x00002d74, 0x00002d89, 0x00002f09,
	0x00002f1d, 0x00002f98, 0x00002fb7, 0x00002ffb,
	0x00003016, 0x00003073, 0x00003078, 0x00003083,
	0x000030a3, 0x000030af, 0x00003154, 0x0000315f,
	0x00003184, 0x000031ae, 0x000031c0, 0x000031ca,
	// Entry 160 - 17F
	0x000031d7, 0x000031e6, 0x000031ec, 0x0000320d,
	0x00003229, 0x0000325d, 0x00003270, 0x00003285,
} // Size: 1464 bytes

const en_USData string = "" + // Size: 12933 bytes
	"\x02Please choose a method to authenticate the agent:\x02ID\x02Name\x02D" +
	"escription\x02Link\x02Required environment variables:\x02Args\x02Env\x02" +
	"Type to start a conversation, press Shift+Enter to send\x02Send\x02Stop" +
	"\x02Off\x02On\x02Options\x02Type @ to include resource, and / to use ski" +
	"lls.\x02No messages.\x02Thinking\x02Plan\x02Raw Input\x02Raw Output\x02T" +
	"erminal: %[1]s\x02Copy\x02Cut\x02Paste\x02Find & Replace\x02Lock\x02Unlo" +
	"ck\x02Unwrap Lines\x02Wrap Lines\x02Match Case\x02Whole Word\x02Use Rege" +
	"x\x02No results\x02%[1]d of %[2]d\x02Replace\x02Replace All\x02Ln %[1]d," +
	" Col %[2]d\x04\x01 \x00\x11\x02(%[1]d selected)\x02Exit\x02Choose your L" +
	"ibrary folder\x02Select the folder that contains your courses, notebooks" +
	", and documents. Typstify keeps it as a normal folder.\x02Choose folder" +
	"\x02Sign In\x02Start\x02Typstify\x02Crafting Typst documents at the spee" +
	"d of thought.\x02Welcome, %[1]s!\x02Getting Started\x02New project..." +
	"\x02Open existing project...\x02Browse Packages/Templates...\x02Learn mo" +
	"re\x04\x00\x01 $\x02To learn more about Typstify, go to\x04\x00\x01  " +
	"\x02To learn more about TPIX, click\x02Open/Hide File Explorer: %[1]s + " +
	"D\x02Open/Hide Console: %[1]s + K\x02Open/Hide Previewer: %[1]s + P\x02O" +
	"pen AI Assistant: %[1]s + L\x02Starting AI Assistant...\x02Sessions\x02N" +
	"ew chat\x02No previous chats yet.\x02Sync Bibliography\x02Submit\x02Crea" +
	"ting managed bibliography error: %[1]s\x02Creating managed bibliography " +
	"succeeded: %[1]s\x02Bibliography File Name\x02The name of the managed bi" +
	"bliography file, such as 'bib-file-name.bib'. You can leave it empty to " +
	"use a auto generated one.\x02Collections\x04\x00\x01 i\x02Select the col" +
	"lection to sync with. Make sure you or your team have added Zotero API k" +
	"ey on TPIX server.\x02Loading collecions...\x02No collections found\x02V" +
	"iew Managed Bibliography\x02Unlink\x02Unlink managed bibliography error:" +
	" %[1]s\x02Unlink managed bibliography succeeded: %[1]s\x02The path of th" +
	"e managed bibliography file. Clicking unlink below will turn it to a reg" +
	"ular file, and it will not sync with remote Zotero collection anymore." +
	"\x02Format:\x02Zotero Collection Info\x02Namespace: %[1]s\x02Library: %[" +
	"1]s\x02Collection: %[1]s\x02Create New Project\x02Create\x02Please set a" +
	" name for your project.\x02Please open a folder in File Explorer to plac" +
	"e the project files.\x02Please input a valid full template name.\x02Not " +
	"a package creation request.\x02Please set a name for your package/templa" +
	"te.\x02Please select where the project should be created.\x02Create proj" +
	"ect error: %[1]s\x02Project Type\x02Choose Document for notes, articles," +
	" books, or slides. Choose Package or Template only when developing reusa" +
	"ble Typst packages.\x02Project Location\x02Select the folder where the p" +
	"roject will be created.\x02Create In\x02The project will be created insi" +
	"de the current Library folder.\x02Select a directory\x02Typst Template" +
	"\x02Optionally start from a Typst package such as @preview/aero-check:0." +
	"1.1. Leave this empty to create a basic document.\x02@preview/package:ve" +
	"rsion (optional)\x02Project Name\x02A folder with this name will be crea" +
	"ted at the location above.\x02Project name\x02Package\x02Template\x02Doc" +
	"ument\x02Delete File/Folder\x02Confirm\x02Are you sure you want to delet" +
	"e '%[1]s'?\x02You can restore this file from the Trash.\x02Cancel\x02Mov" +
	"e File/Folder\x02Are you sure you want to move\x02'%[1]s' into '%[2]s'" +
	"\x02The format of the output file.\x02Build And Export\x02Export\x02Expo" +
	"rting file...\x02Exported File Format\x02Pages\x02Which pages to export." +
	" Valid value can be comma seperated page numbers and page ranges, for ex" +
	"ample, 1,3,5,6-9. When unspecified, all document pages are exported.\x02" +
	"File Name\x02This specifies the output file name. If multiple files is g" +
	"enerated, the file name will be suffixed with a number. When not specifi" +
	"ed, the name of the source file is used.\x02PPI\x02The PPI (pixels per i" +
	"nch) to use for PNG export.\x02PDF Versions\x02PDF version that Typstify" +
	" will enforce conformance with.\x02PDF Standards\x02PDF standards that T" +
	"ypstify will enforce conformance with.\x02Disable PDF Tags\x02By default" +
	" a tagged PDF is generated to provide base accessibility. In some cases " +
	"this may be not desired. You can check this to disable it.\x02No PDF Tag" +
	"s\x02Change File Indentation\x02Indent with spaces or tabs\x02Choose the" +
	" indentation style for the current file.\x02Tab Width\x02Change tab disp" +
	"lay size.\x02Convert the indentation\x02Convert the indentation from spa" +
	"ces to tabs or from tabs to spaces, depending on what you choosed.\x02Op" +
	"en File With...\x02Are you sure you want to open file '%[1]s'?\x02Publis" +
	"h Package\x02publish package error: %[1]s\x02publish package succeeded: " +
	"%[1]s\x02Bundle\x02Bundle the project files to a valid Typst package/tem" +
	"plate.\x02Build\x02Created Bundle: %[1]s\x02Namespace\x04\x00\x01 \x86" +
	"\x01\x02Select the namespace to publish to. Make sure you have logged in" +
	" TPIX in the app and have accessible namespaces of your TPIX account." +
	"\x02Loading namespaces...\x02No writable namespaces\x02Search & Replace" +
	"\x02Preview\x02AI Assistant\x02Paste asset: %[1]s\x02Explorer\x02No proj" +
	"ect\x02No open project.\x02Project\x02Folder\x02pull dependencies error:" +
	" %[1]s\x02pull dependencies succeeded!\x02Sync Dependencies\x02Sync Bibl" +
	"iographies\x02View Bibliography Info\x02No items match this filter.\x02T" +
	"his folder is empty. Use New to create a file, folder, or project.\x02%[" +
	"1]d items\x02New\x02New File\x02New Folder\x02New Project\x02Notebook" +
	"\x02File\x02Typst work\x02Notebooks\x02Typst documents\x02PDFs\x02Images" +
	"\x02Other files\x02All files\x02Hide Explorer\x02Library\x02Open Folder" +
	"\x02Typst Package Center\x02Settings\x02Files\x02Outline\x02Assistant" +
	"\x02More\x02Local Templates\x02File Explorer\x02A new version is avaliab" +
	"le: %[1]s\x02Later\x02Download\x02Cached\x02Author\x02Last Updated\x02Li" +
	"cense\x02Category\x02Read the docs\x02Copy import path\x02Loading packag" +
	"es...\x02No packages/templates found\x02Clear\x02Typst Packages\x02Searc" +
	"h packages/templates on TPIX\x02Browsing thousands of packages and templ" +
	"ates on TPIX server, including public namespaces, and private namespaces" +
	" of your teams.\x02Search TPIX...\x02Personal @local packages and templa" +
	"tes from Typst's local package folder. No account or network connection " +
	"is required.\x02Search local templates...\x02Package kind\x02Use templat" +
	"e\x02Query packages...\x04\x00\x01 \x17\x02Query packages failed:\x02Typ" +
	"st packages info loaded.\x04\x00\x01 \x19\x02Download package failed:" +
	"\x04\x00\x01 \x1a\x02Downloaded package %[1]s.\x02Downloaded package %[1" +
	"]s and %[2]d transitive dependencies.\x02Found %[1]d packages.\x02Found " +
	"%[1]d local templates.\x02All\x02Agent\x02Configure agent for AI assitan" +
	"t. You can either manually configure your own agent, or select one from " +
	"the Agent Registry below.\x02Agent Registry\x02Select an agent from the " +
	"registry. Click use to overwrite the above configuration.\x02MCP\x02The " +
	"built-in MCP server use dynamic network port by default, and it register" +
	"s itself to agent at runtime. \x0aSome agents does not support runtime r" +
	"egistration, you have to fix the MCP server port and register the server" +
	" manually. When using static port, the server address is 127.0.0.1:5322," +
	" transport: http.\x02Use\x02Refresh\x02ID:\x02Version:\x02License:\x02Au" +
	"thors:\x02Repository:\x02Ready — npx is available on your system.\x02Req" +
	"uires Node.js. Install from https://nodejs.org, then restart Typstify." +
	"\x02If the agent fails to start, try installing manually: npm install -g" +
	" %[1]s\x02Installation (npx)\x02Ready — uvx is available on your system." +
	"\x02Requires uvx. Install via `pip install uv` or https://docs.astral.sh" +
	"/uv, then restart Typstify.\x02If the agent fails to start, try installi" +
	"ng manually: uv pip install %[1]s\x02Installation (uvx)\x02Installation " +
	"(Binary)\x02Download the archive for your platform, extract it, and ensu" +
	"re the binary is on your PATH.\x02Installation\x02This agent is not dire" +
	"ctly available for your platform. Visit the ACP registry for more detail" +
	"s.\x02See https://agentclientprotocol.com/get-started/registry\x02Agent " +
	"Name\x02Select an agent below or type a name directly.\x02Command\x02Sel" +
	"ect an agent below or edit directly, e.g. npx -y @scope/package\x02npx -" +
	"y @scope/package\x02Environment\x02Extra environment variables, space-se" +
	"parated KEY=value pairs, e.g. FOO=bar BAZ=qux\x02FOO=bar BAZ=qux\x02Vers" +
	"ion\x02Preview In Browser\x02When checked, document preview will be open" +
	"ing in your default browser. Otherwise the preview will use built-in pre" +
	"viewer.\x02Enable Partial Preview\x02The previewer will only render page" +
	"s inside the viewport if enabled. This improves performance especially f" +
	"or large document.\x02Debug Log\x02When checked, logs from the built-in " +
	"LSP (Language Server Procotol) server is written to the console panel. I" +
	"t needs to restart or reload to take effect.\x02Power Saving\x02When che" +
	"cked, LSP server runs in power saving mode, only basic syntax checking a" +
	"nd code completion are avaliable, diagnostics and previewing will not wo" +
	"rk. It needs to restart or reload to take effect.\x02Language Server\x02" +
	"Language\x02Set the displaying language of the user interface.\x02UI Tex" +
	"t Size\x02Set font size for the user interface. The unit is in scale-ind" +
	"ependent pixel (sp).\x02UI Font Family\x02Set the desired fonts for the " +
	"UI. Use CSS style font family syntax which is a list of comma separated " +
	"names. You can also leave it empty to let the application choose a fallb" +
	"ack.\x02Font Family\x02Theme\x02Choose your favorite color theme for the" +
	" user interface.\x02External Typst Compiler Path\x02Specifies a path to " +
	"your own version of Typst compiler. Leave it empty to use the built-in o" +
	"ne. Please check the compatibility before you switch. It needs to restar" +
	"t to take effect.\x02External LSP Server(Tinymist) Path\x02Specifies a p" +
	"ath to your own version of Tinymist. Leave it empty to use the built-in " +
	"one. Please check the compatibility before you switch. It needs to resta" +
	"rt to take effect.\x02Check Update\x02Check for updates on app startup. " +
	"Please enable it to keep up to date for new features and bugfixes.\x02Ge" +
	"neral\x02Auto Save Interval\x02Set the auto save delay (in seconds), can" +
	"not be completely disabled.\x02Preview width\x02Choose how much editor s" +
	"pace the preview uses when it opens. You can still drag the divider whil" +
	"e editing.\x02Set the desired fonts for the editor. Use CSS style font f" +
	"amily syntax which is a list of comma separated names. You can also leav" +
	"e it empty to let the application choose a fallback.\x02Text Size\x02Set" +
	" font size for the editor. The unit is in scale-independent pixel (sp)." +
	"\x02Font Weight\x02Set the expected weight (or boldness) of the text. Th" +
	"is is for variable fonts only.\x02Line Height Scale\x02Set the line heig" +
	"ht scale of the lines in editor. Line height scale is multiplied by line" +
	" height to determine the final gap between lines.\x02Indentation\x02Set " +
	"the expected characters to use when pressing the Tab key. Please be note" +
	"d that this works only for empty file. Indentation for non-empty files a" +
	"re auto detected.\x02Set how many number of spaces the Tab is equal to. " +
	"Please be noted that this works only for empty file. Indentation for non" +
	"-empty files are auto detected.\x02Editor\x02File Interface\x02Interface" +
	"\x02Classic keeps Typstify's existing file workflow. Student adds a Libr" +
	"ary home and focused project navigation.\x02Classic\x02Student\x02Your S" +
	"tudent preferences are saved and will return when you choose Student." +
	"\x02Student preferences\x02These choices apply immediately and do not ch" +
	"ange the Classic interface.\x02Library folder\x02The folder shown when S" +
	"tudent mode starts. Forgetting it does not delete any files.\x02No Libra" +
	"ry folder selected\x02Change\x02Forget\x02Editor files\x02Show only the " +
	"current project or folder, or keep the complete workspace tree.\x02Curre" +
	"nt project or folder\x02Whole workspace\x02Library view\x02Choose the de" +
	"fault presentation for folders, notebooks, and files.\x02Grid\x02List" +
	"\x02Navigation\x02Use the Library rail, or keep Typstify's familiar side" +
	"bar and bottom controls.\x02Library rail\x02Classic controls\x02Typst" +
	"\x02Package Dir\x02Specifies where to store your local Typst packages/te" +
	"mplates. Leave it empty to use the default dir.\x02Package Cache Dir\x02" +
	"Specifies where to store your the cached Typst packages/templates retrie" +
	"ved from the network. Leave it empty to use the default dir.\x02Extra Fo" +
	"nt Path\x02The directory where to search for fonts when exporting, previ" +
	"ewing and auto-completing. Be aware that the current project root direct" +
	"ory is always searched. Need to restart or reload to take effect.\x02Exp" +
	"ort Dir\x02The directory to save exported files to, including the deps.j" +
	"son. If not set, the exported files will be saved to a 'output' folder b" +
	"eside the source file.\x02Load External Inputs\x02Load external inputs f" +
	"rom a file named sys-inputs.json as sys.inputs. If there is no such one," +
	" it is created at the root dir. \x0aA sys-inputs.json file contains user" +
	" defined key-value pairs which can be accessed via Typst's sys.inputs. T" +
	"he values should always be string encoded data.\x0aNeed to restart or re" +
	"load to take effect for code linter, auto-completion, and preview when c" +
	"hanged.\x02Ignore System Fonts\x02Ignore system fonts or not. For code l" +
	"inter, auto-completion and previewing, it needs to restart or reload to " +
	"take effect.\x02Ignore Compiler Embedded Fonts\x02Ignore embedded Fonts " +
	"or not. This only works when exporting files.\x02Generate Dependencies f" +
	"ile\x02Write dependencies of the file compiled to a file named deps.json" +
	" in your project directory.\x02TPIX\x02Loading...\x02You have an active " +
	"TPIX session\x02Logout TPIX\x02Login TPIX to access all the features of " +
	"Typstify, including package management, Zotero sync, MCP tools for AI as" +
	"sistant etc. Some features may need a subscription.\x02Login TPIX\x04" +
	"\x00\x01  \x02To learn more about TPIX, go to\x04\x00\x01 %\x02To get a " +
	"subscription of TPIX, click\x02Check new version\x02Changelog\x02Release" +
	" Time\x02Go to download\x02About\x02git checkout %[1]s failed: %[2]v\x02" +
	"Width: %[1]d, Height: %[2]d\x02popup and display the preview in a dedica" +
	"ted window\x02Open File Location\x02Open Folder Location"

var zh_CNIndex = []uint32{ // 360 elements
	// Entry 0 - 1F
	0x00000000, 0x00000025, 0x00000028, 0x0000002f,
	0x00000036, 0x0000003d, 0x00000056, 0x0000005d,
	0x0000006a, 0x00000099, 0x000000a0, 0x000000a7,
	0x000000ab, 0x000000af, 0x000000b6, 0x000000e4,
	0x000000f1, 0x000000fb, 0x00000102, 0x0000010f,
	0x0000011c, 0x0000012a, 0x00000131, 0x00000138,
	0x0000013f, 0x0000014f, 0x00000156, 0x0000015d,
	0x0000016a, 0x00000177, 0x00000187, 0x00000194,
	// Entry 20 - 3F
	0x000001a1, 0x000001ab, 0x000001b9, 0x000001c0,
	0x000001cd, 0x000001e2, 0x00000204, 0x0000020b,
	0x00000224, 0x00000288, 0x00000298, 0x0000029f,
	0x000002a6, 0x000002af, 0x000002d8, 0x000002e7,
	0x000002f4, 0x00000304, 0x0000031a, 0x0000032e,
	0x0000033b, 0x00000369, 0x00000393, 0x000003bb,
	0x000003dd, 0x000003ff, 0x0000041b, 0x00000435,
	0x0000043c, 0x00000449, 0x00000462, 0x00000475,
	// Entry 40 - 5F
	0x0000047c, 0x000004a2, 0x000004c8, 0x000004de,
	0x00000541, 0x00000548, 0x000005ba, 0x000005d0,
	0x000005e0, 0x000005f9, 0x00000606, 0x00000632,
	0x0000065e, 0x000006df, 0x000006e7, 0x000006fb,
	0x0000070f, 0x0000071d, 0x0000072b, 0x0000073b,
	0x00000742, 0x00000764, 0x000007aa, 0x000007d2,
	0x000007f1, 0x0000081d, 0x0000083f, 0x00000859,
	0x00000866, 0x000008e9, 0x000008f6, 0x0000091b,
	// Entry 60 - 7F
	0x00000928, 0x00000959, 0x00000966, 0x00000973,
	0x000009d2, 0x000009f7, 0x00000a04, 0x00000a2f,
	0x00000a3c, 0x00000a40, 0x00000a47, 0x00000a4e,
	0x00000a65, 0x00000a6c, 0x00000a89, 0x00000ab1,
	0x00000ab8, 0x00000acf, 0x00000adf, 0x00000af8,
	0x00000b11, 0x00000b21, 0x00000b28, 0x00000b3e,
	0x00000b51, 0x00000b58, 0x00000bdb, 0x00000be5,
	0x00000c5b, 0x00000c5f, 0x00000c92, 0x00000c9d,
	// Entry 80 - 9F
	0x00000cc7, 0x00000cd2, 0x00000cfc, 0x00000d0e,
	0x00000d8f, 0x00000d9e, 0x00000db1, 0x00000dd0,
	0x00000df5, 0x00000e05, 0x00000e24, 0x00000e31,
	0x00000e8c, 0x00000ea2, 0x00000ec5, 0x00000ecf,
	0x00000ee6, 0x00000efd, 0x00000f04, 0x00000f3a,
	0x00000f41, 0x00000f5e, 0x00000f6b, 0x00000fe5,
	0x00001001, 0x0000101d, 0x0000102d, 0x00001034,
	0x0000103d, 0x00001052, 0x00001062, 0x0000106c,
	// Entry A0 - BF
	0x00001085, 0x0000108c, 0x00001096, 0x000010b0,
	0x000010c4, 0x000010d1, 0x000010e4, 0x000010fd,
	0x00001125, 0x00001171, 0x00001181, 0x00001188,
	0x00001195, 0x000011a5, 0x000011b2, 0x000011bc,
	0x000011c3, 0x000011d0, 0x000011da, 0x000011e7,
	0x000011eb, 0x000011f2, 0x000011ff, 0x0000120c,
	0x00001222, 0x0000122c, 0x0000123c, 0x0000124c,
	0x00001253, 0x0000125a, 0x00001261, 0x00001268,
	// Entry C0 - DF
	0x0000126f, 0x0000127c, 0x00001292, 0x000012ac,
	0x000012b3, 0x000012ba, 0x000012c4, 0x000012cb,
	0x000012d8, 0x000012e2, 0x000012e9, 0x000012f6,
	0x00001309, 0x0000131c, 0x00001330, 0x00001337,
	0x00001341, 0x0000135e, 0x000013ce, 0x000013dd,
	0x0000143b, 0x00001451, 0x0000145b, 0x00001468,
	0x00001475, 0x0000148b, 0x000014a7, 0x000014bd,
	0x000014d8, 0x00001508, 0x0000151f, 0x0000153f,
	// Entry E0 - FF
	0x00001546, 0x0000154c, 0x000015c0, 0x000015d0,
	0x00001619, 0x0000161d, 0x00001722, 0x00001729,
	0x00001730, 0x00001734, 0x0000173c, 0x00001744,
	0x0000174c, 0x00001754, 0x00001773, 0x000017c0,
	0x00001807, 0x0000181a, 0x00001839, 0x000018a1,
	0x000018e8, 0x000018fb, 0x00001914, 0x00001972,
	0x0000197f, 0x000019d6, 0x00001a15, 0x00001a22,
	0x00001a5b, 0x00001a62, 0x00001ab0, 0x00001ac6,
	// Entry 100 - 11F
	0x00001ad3, 0x00001b26, 0x00001b36, 0x00001b3d,
	0x00001b53, 0x00001bb4, 0x00001bc7, 0x00001c2b,
	0x00001c38, 0x00001cc1, 0x00001cce, 0x00001d81,
	0x00001d91, 0x00001d98, 0x00001dbd, 0x00001dcd,
	0x00001e15, 0x00001e1f, 0x00001ebc, 0x00001ec3,
	0x00001eca, 0x00001ef8, 0x00001f15, 0x00001f9e,
	0x00001fc4, 0x00002047, 0x00002054, 0x000020a9,
	0x000020b0, 0x000020c3, 0x000020fd, 0x0000210a,
	// Entry 120 - 13F
	0x0000215c, 0x000021fe, 0x0000220b, 0x00002250,
	0x0000225d, 0x000022ac, 0x000022b9, 0x00002323,
	0x0000232a, 0x000023a2, 0x00002414, 0x0000241e,
	0x0000242b, 0x00002432, 0x000024a6, 0x000024ad,
	0x000024b4, 0x00002500, 0x00002513, 0x0000254d,
	0x00002560, 0x000025b8, 0x000025d4, 0x000025db,
	0x000025e2, 0x000025f2, 0x0000263e, 0x00002657,
	0x00002667, 0x00002677, 0x000026b4, 0x000026bb,
	// Entry 140 - 15F
	0x000026c2, 0x000026c9, 0x0000271c, 0x0000272f,
	0x0000273c, 0x00002742, 0x0000274c, 0x0000279a,
	0x000027aa, 0x0000280d, 0x00002820, 0x000028ba,
	0x000028c7, 0x0000294e, 0x00002961, 0x00002ac0,
	0x00002ad3, 0x00002b46, 0x00002b62, 0x00002b9c,
	0x00002baf, 0x00002bfa, 0x00002bff, 0x00002c0c,
	0x00002c2e, 0x00002c3a, 0x00002ccc, 0x00002cd8,
	0x00002d02, 0x00002d26, 0x00002d36, 0x00002d43,
	// Entry 160 - 17F
	0x00002d50, 0x00002d5d, 0x00002d64, 0x00002d85,
	0x00002da2, 0x00002dca, 0x00002de3, 0x00002dff,
} // Size: 1464 bytes

const zh_CNData string = "" + // Size: 11775 bytes
	"\x02请选择一种方式验证代理：\x02ID\x02名称\x02描述\x02链接\x02需要的环境变量：\x02参数\x02环境变量\x02输入" +
	"以开始对话，按 Shift+Enter 发送\x02发送\x02停止\x02关\x02开\x02选项\x02输入 @ 引用资源，输入 / 使" +
	"用技能\x02暂无消息\x02思考中\x02计划\x02原始输入\x02原始输出\x02终端: %[1]s\x02复制\x02剪切\x02粘" +
	"贴\x02查找与替换\x02锁定\x02解锁\x02取消换行\x02自动换行\x02区分大小写\x02全词匹配\x02使用正则\x02无结果" +
	"\x02%[1]d / %[2]d\x02替换\x02全部替换\x02行 %[1]d, 列 %[2]d\x04\x01 \x00\x1d\x02" +
	"（已选 %[1]d 个字符）\x02退出\x02选择资料库文件夹\x02选择包含课程、笔记本和文档的文件夹。Typstify 会将其保留为普" +
	"通文件夹。\x02选择文件夹\x02登陆\x02开始\x02Typstify\x02以思维的速度编写 Typst 文档。\x02欢迎, %[" +
	"1]s!\x02开始使用\x02新建项目...\x02打开已有项目...\x02浏览包/模板...\x02了解更多\x04\x00\x01 )" +
	"\x02了解更多 Typstify 信息，请访问\x04\x00\x01 %\x02了解更多 TPIX 信息，请访问\x02打开/隐藏文件管理器" +
	": %[1]s + D\x02打开/隐藏控制台: %[1]s + K\x02打开/隐藏预览器: %[1]s + P\x02打开 AI 助手: %" +
	"[1]s + L\x02正在启动 AI 助手...\x02会话\x02新建聊天\x02还没有历史聊天。\x02同步参考文献\x02提交\x02创" +
	"建托管参考文献出错: %[1]s\x02创建托管参考文献成功: %[1]s\x02参考文献文件名\x02托管参考文献文件名，例如 'bib-" +
	"file-name.bib'。留空则使用自动生成的名称。\x02集合\x04\x00\x01 m\x02选择要同步的集合。请确保您或您的团队已在" +
	" TPIX 服务器上添加了 Zotero API 密钥。\x02正在加载集合...\x02未找到集合\x02查看托管参考文献\x02取消关联" +
	"\x02取消关联托管参考文献出错: %[1]s\x02取消关联托管参考文献成功: %[1]s\x02托管参考文献文件路径。点击下方的取消关联将把" +
	"它转为普通文件，不再与远程 Zotero 集合同步。\x02格式:\x02Zotero 集合信息\x02命名空间: %[1]s\x02文库:" +
	" %[1]s\x02集合: %[1]s\x02创建新项目\x02创建\x02请为项目设置一个名称。\x02请在文件管理器中选择一个文件夹来放置项" +
	"目文件。\x02请输入有效的完整模板名称。\x02这不是创建包的请求。\x02请为您的包/模板设置一个名称。\x02请选择项目的创建位置。" +
	"\x02创建项目出错: %[1]s\x02项目类型\x02为笔记、文章、书籍或幻灯片选择“文档”。仅在开发可复用的 Typst 包时选择“包”或" +
	"“模板”。\x02项目位置\x02选择要创建项目的文件夹。\x02创建位置\x02项目将在当前资料库文件夹中创建。\x02选择目录\x02T" +
	"ypst 模板\x02可以选择从 @preview/aero-check:0.1.1 等 Typst 包开始。留空则创建基本文档。\x02@pr" +
	"eview/package:version（可选）\x02项目名称\x02将在上方位置创建同名文件夹。\x02项目名称\x02包\x02模板" +
	"\x02文档\x02删除文件/文件夹\x02确认\x02确定要删除 '%[1]s' 吗?\x02您可以从回收站恢复此文件。\x02取消\x02移" +
	"动文件/文件夹\x02确定要移动\x02'%[1]s' 到 '%[2]s' 吗?\x02输出文件的格式。\x02构建并导出\x02导出" +
	"\x02正在导出文件...\x02导出文件格式\x02页面\x02要导出的页面。有效值可以是逗号分隔的页码和页码范围，例如 1,3,5,6-9。" +
	"未指定时导出所有页面。\x02文件名\x02指定输出文件名。如果生成多个文件，文件名将附带数字后缀。未指定时使用源文件名。\x02PPI" +
	"\x02PNG 导出使用的 PPI（每英寸像素数）。\x02PDF 版本\x02Typstify 将强制遵循的 PDF 版本。\x02PDF 标" +
	"准\x02Typstify 将强制遵循的 PDF 标准。\x02禁用 PDF 标签\x02默认生成带标签的 PDF 以提供基本的可访问性。在" +
	"某些情况下可能不需要。勾选此选项可禁用它。\x02无 PDF 标签\x02更改文件缩进\x02使用空格或制表符缩进\x02选择当前文件的缩进" +
	"样式。\x02制表符宽度\x02更改制表符显示宽度。\x02转换缩进\x02根据您的选择，将缩进从空格转换为制表符或从制表符转换为空格。" +
	"\x02选择打开方式...\x02确定要打开文件 '%[1]s' 吗?\x02发布包\x02发布包出错: %[1]s\x02发布包成功: %[1" +
	"]s\x02打包\x02将项目文件打包为有效的 Typst 包/模板。\x02构建\x02已创建打包文件: %[1]s\x02命名空间\x04" +
	"\x00\x01 u\x02选择要发布到的命名空间。请确保您已在应用中登录 TPIX，并且拥有可访问的命名空间。\x02正在加载命名空间..." +
	"\x02没有可写的命名空间\x02搜索和替换\x02预览\x02AI助手\x02粘贴资源：%[1]s\x02文件浏览器\x02无项目\x02没有" +
	"打开的项目。\x02项目\x02文件夹\x02拉取依赖出错: %[1]s\x02拉取依赖成功!\x02同步依赖\x02同步参考文献\x02查" +
	"看参考文献信息\x02没有符合此筛选条件的项目。\x02此文件夹为空。使用“新建”创建文件、文件夹或项目。\x02%[1]d 个项目\x02" +
	"新建\x02新建文件\x02新建文件夹\x02新建项目\x02笔记本\x02文件\x02Typst 工作\x02笔记本\x02Typst 文" +
	"档\x02PDF\x02图片\x02其他文件\x02所有文件\x02隐藏资源管理器\x02资料库\x02打开文件夹\x02Typst 包中心" +
	"\x02设置\x02文件\x02大纲\x02助手\x02更多\x02本地模板\x02文件资源管理器\x02有新版本可用: %[1]s\x02稍后" +
	"\x02下载\x02已缓存\x02作者\x02最后更新\x02许可证\x02分类\x02阅读文档\x02复制导入路径\x02正在加载包..." +
	"\x02未找到包/模板\x02清除\x02Typst 包\x02在 TPIX 上搜索包/模板\x02浏览 TPIX 服务器上的数千个包和模板，包" +
	"括公共命名空间和您团队的私有命名空间。\x02搜索 TPIX...\x02来自 Typst 本地包文件夹的个人 @local 包和模板。无需" +
	"账户或网络连接。\x02搜索本地模板…\x02包类型\x02使用模板\x02查询包...\x04\x00\x01 \x11\x02查询包失败" +
	":\x02Typst 包信息已加载。\x04\x00\x01 \x11\x02下载包失败:\x04\x00\x01 \x16\x02已下载包 %" +
	"[1]s。\x02已下载包 %[1]s 及 %[2]d 个传递依赖。\x02找到 %[1]d 个包。\x02找到 %[1]d 个本地模板。" +
	"\x02全部\x02Agent\x02为 AI 助手配置代理。您可以手动配置自己的代理，或从下方的代理注册表中选择一个。\x02代理注册表" +
	"\x02从注册表中选择一个代理。点击使用以覆盖上述配置。\x02MCP\x02内置 MCP 服务器默认使用动态网络端口，并在运行时向代理注册。" +
	"\x0a某些代理不支持运行时注册，您需要固定 MCP 服务器端口并手动注册。使用静态端口时，服务器地址为 127.0.0.1:5322，传输方式" +
	": http。\x02使用\x02刷新\x02ID:\x02版本:\x02许可:\x02作者:\x02仓库:\x02就绪 — 系统可用 npx。" +
	"\x02需要 Node.js。请从 https://nodejs.org 安装，然后重启 Typstify。\x02如果代理启动失败，请尝试手动" +
	"安装: npm install -g %[1]s\x02安装方式 (npx)\x02就绪 — 系统可用 uvx。\x02需要 uvx。请通过" +
	" `pip install uv` 或 https://docs.astral.sh/uv 安装，然后重启 Typstify。\x02如果代理启" +
	"动失败，请尝试手动安装: uv pip install %[1]s\x02安装方式 (uvx)\x02安装方式 (二进制)\x02下载适用于" +
	"您平台的压缩包，解压后确保将二进制文件添加到 PATH 中。\x02安装方式\x02该代理不直接适用于您的平台。请访问 ACP 注册表了解更" +
	"多详情。\x02请参见 https://agentclientprotocol.com/get-started/registry\x02代理" +
	"名称\x02从下面选择一个Agent或者直接输入一个名字\x02命令\x02从下面选择一个Agent或者直接输入，例如：npx -y @sc" +
	"ope/package\x02npx -y @scope/package\x02环境变量\x02额外的环境变量，空格分隔的 KEY=值 键值对，" +
	"例如 FOO=bar BAZ=qux\x02FOO=bar BAZ=qux\x02版本\x02在浏览器中预览\x02勾选后，文档预览将在默认" +
	"浏览器中打开。否则预览将使用内置预览器。\x02启用局部预览\x02启用后，预览器仅渲染可见区域内的页面。这尤其能提升大型文档的性能。" +
	"\x02调试日志\x02勾选后，内置 LSP（语言服务器协议）服务器的日志将写入控制台面板。需要重启或重新加载才能生效。\x02省电模式\x02" +
	"勾选后，LSP 服务器将运行在省电模式，仅提供基本语法检查和代码补全功能，诊断和预览将无法使用。需要重启或重新加载才能生效。\x02语言服务" +
	"器\x02语言\x02设置用户界面的显示语言。\x02UI 文字大小\x02设置用户界面的字体大小。单位为缩放无关像素 (sp)。\x02U" +
	"I 字体\x02设置 UI 所需的字体。使用 CSS 样式的字体族语法，即以逗号分隔的名称列表。您也可以留空让应用程序选择后备字体。\x02字体" +
	"\x02主题\x02选择您喜欢的用户界面颜色主题。\x02外部 Typst 编译器路径\x02指定您自己的 Typst 编译器版本路径。留空则使" +
	"用内置版本。切换前请检查兼容性。需要重启才能生效。\x02外部 LSP 服务器(Tinymist) 路径\x02指定您自己的 Tinymis" +
	"t 版本路径。留空则使用内置版本。切换前请检查兼容性。需要重启才能生效。\x02检查更新\x02应用启动时检查更新。请启用以保持获取最新功能和错" +
	"误修复。\x02通用\x02自动保存间隔\x02设置自动保存延迟（秒），无法完全禁用。\x02预览宽度\x02选择预览打开时占用的编辑器空间" +
	"。编辑时仍可拖动分隔线。\x02设置编辑器所需的字体。使用 CSS 样式的字体族语法，即以逗号分隔的名称列表。您也可以留空让应用程序选择后备" +
	"字体。\x02文字大小\x02设置编辑器的字体大小。单位为缩放无关像素 (sp)。\x02字体粗细\x02设置文本的预期粗细（或加粗程度）。" +
	"仅适用于可变字体。\x02行高倍率\x02设置编辑器中行的行高倍率。行高倍率乘以行高以确定行与行之间的最终间距。\x02缩进\x02设置按 " +
	"Tab 键时要使用的字符。请注意，这仅适用于空文件。非空文件的缩进将自动检测。\x02设置 Tab 等于多少个空格。请注意，这仅适用于空文件。非" +
	"空文件的缩进将自动检测。\x02编辑器\x02文件界面\x02界面\x02“经典”保留 Typstify 现有的文件工作流。“学生”增加资料" +
	"库主页和聚焦的项目导航。\x02经典\x02学生\x02学生模式偏好会被保存，并在再次选择“学生”时恢复。\x02学生模式偏好\x02这些选" +
	"项立即生效，且不会更改经典界面。\x02资料库文件夹\x02学生模式启动时显示的文件夹。忘记该文件夹不会删除任何文件。\x02未选择资料库文" +
	"件夹\x02更改\x02忘记\x02编辑器文件\x02仅显示当前项目或文件夹，或保留完整的工作区文件树。\x02当前项目或文件夹\x02整个" +
	"工作区\x02资料库视图\x02选择文件夹、笔记本和文件的默认显示方式。\x02网格\x02列表\x02导航\x02使用资料库导航栏，或保留" +
	" Typstify 熟悉的侧边栏和底部控件。\x02资料库导航栏\x02经典控件\x02Typst\x02包目录\x02指定存储本地 Typst" +
	" 包/模板的位置。留空则使用默认目录。\x02包缓存目录\x02指定存储从网络获取的已缓存 Typst 包/模板的位置。留空则使用默认目录。" +
	"\x02额外字体路径\x02导出、预览和自动补全时搜索字体的目录。请注意，当前项目根目录始终会被搜索。需要重启或重新加载才能生效。\x02导出目" +
	"录\x02保存导出文件的目录，包括 deps.json。如果未设置，导出文件将保存到源文件旁边的 'output' 文件夹中。\x02加载外" +
	"部输入\x02从名为 sys-inputs.json 的文件加载外部输入作为 sys.inputs。如果没有此文件，将在根目录创建。\x0a" +
	"sys-inputs.json 文件包含用户定义的键值对，可通过 Typst 的 sys.inputs 访问。值应始终为字符串编码数据。\x0a" +
	"更改后需要重启或重新加载才能对代码检查器、自动补全和预览生效。\x02忽略系统字体\x02是否忽略系统字体。对于代码检查、自动补全和预览，需" +
	"要重启或重新加载才能生效。\x02忽略编译器嵌入字体\x02是否忽略嵌入字体。仅在导出文件时生效。\x02生成依赖文件\x02将编译文件的依" +
	"赖写入项目目录中名为 deps.json 的文件。\x02TPIX\x02加载中...\x02您有一个活跃的 TPIX 会话\x02登出 T" +
	"PIX\x02登录 TPIX 以访问 Typstify 的所有功能，包括包管理、Zotero 同步、AI 助手的 MCP 工具等。部分功能可能需" +
	"要订阅。\x02登录 TPIX\x04\x00\x01 %\x02了解更多 TPIX 信息，请访问\x04\x00\x01 \x1f\x02" +
	"获取 TPIX 订阅，请点击\x02检查新版本\x02更新日志\x02发布时间\x02前往下载\x02关于\x02git checkout " +
	"%[1]s 失败: %[2]v\x02宽度: %[1]d, 高度: %[2]d\x02弹出并在独立窗口中显示预览\x02打开文件所在位置\x02" +
	"打开文件夹所在位置"

	// Total table size 44919 bytes (43KiB); checksum: 55CF98B9
